

services:
  backend:
    image: wolt-backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod  
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - ./backend/.env
  frontend:
    image: wolt-frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod 
    
    ports:
      - "5173:5173" 
